---

- name: Set up the MiniPiRack to cut the cable
  hosts: master
  become: yes

  roles:
    - btenable
    - wifi
    - nat

- name: Reboot to finish settings
  hosts:
    - master
    - slave

  roles:
    - final
