---

- name: Update repositories cache and install dnsmasq
  apt:
    name: dnsmasq
    update_cache: yes

- name: Set eth0 network file to static
  copy:
    src: eth0
    dest: /etc/network/interfaces.d/eth0
    owner: root
    group: root
    mode: 0644

- name: Install DNSMasq config set for DHCP and DNS
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644

- name: Enable IP forwarding
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net\.ipv4\.ip_forward$'
    line: 'net.ipv4.ip_forward=1'

- name: Verify rc.local exists
  stat:
    path: /etc/rc.local
  register: rc_local_check
  ignore_errors: yes

- name: Copy new rc.local if rc.local does not exist
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0755
  when: rc_local_check.stat.exists == False

- name: Set routing tables
  blockinfile:
    path: /etc/rc.local
    insertbefore: '^exit 0$'
    create: yes
    block: |
        sudo iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
        sudo iptables -A FORWARD -i wlan0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
        sudo iptables -A FORWARD -i eth0 -o wlan0 -j ACCEPT

- name: Delete cloud config file
  file:
    path: /etc/network/interfaces.d/50-cloud-init.cfg
    state: absent
  ignore_errors: yes
